<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="QA-01" failures="1" tests="1" name="com.w2a.testcases.BankManagerLoginTest" time="1.073" errors="0" timestamp="2020-02-10T13:56:04 EET" skipped="0">
  <testcase classname="com.w2a.testcases.BankManagerLoginTest" name="loginBankManager" time="1.073">
    <failure message="Test Failed Intentially" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Test Failed Intentially
at org.testng.Assert.fail(Assert.java:97)
at com.w2a.testcases.BankManagerLoginTest.loginBankManager(BankManagerLoginTest.java:27)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- loginBankManager -->
  <system-out>
Login Succeded TestNG <a target="_blank" href="C:\Users\m.yousaf\Pictures\2019-12-15_1650.png">Screenshot</a> <br> <a target="_blank" href="C:\Users\m.yousaf\Pictures\2019-12-15_1650.png"><img src="C:\Users\m.yousaf\Pictures\2019-12-15_1650.png" height=200 width=200></img></a> Capturing Screenshots <a target="_blank" href="C:\Users\m.yousaf\Pictures\2019-12-15_1650.png">Screenshot</a> <br> <a target="_blank" href="C:\Users\m.yousaf\Pictures\2019-12-15_1650.png"><img src="C:\Users\m.yousaf\Pictures\2019-12-15_1650.png" height=200 width=200></img></a>  </system-out>
</testsuite> <!-- com.w2a.testcases.BankManagerLoginTest -->
